edition = "2024"
# error_on_line_overflow = true
newline_style = "Unix"
single_line_if_else_max_width = 60
single_line_let_else_max_width = 60
use_field_init_shorthand = true
use_try_shorthand = true
