name: Build and Publish Lua Docs

on:
  push:
    branches: ["main"]
    paths:
      - "api/lua/**"
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SSH_DEPLOY_KEY: ${{ secrets.DOCS_DEPLOY_KEY_LUA }}

jobs:
  build-docs:
    runs-on: ubuntu-24.04
    name: Build docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout lcat
        uses: actions/checkout@v4
        with:
          repository: Ottatop/lcat
          path: ./lcat
      - name: Get Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache stuff
        uses: Swatinem/rust-cache@v2
      - name: Extract possible tag version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Generate docs
        run: |
          cd ./lcat
          cargo run -- --dir "../api/lua" --base-url "/lua-reference/${{ env.RELEASE_VERSION || 'main' }}/"
      - name: Push files
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        with:
          source-directory: ./lcat/lcat_out
          destination-github-username: pinnacle-comp
          destination-repository-name: lua-reference
          target-branch: main
          target-directory: ${{ env.RELEASE_VERSION || 'main' }}
