name: Build Rust Docs
on:
  push:
    branches:
      - main
    paths:
      - "api/rust/**"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get protoc
        run: sudo apt install protobuf-compiler
      - name: Extract possible tag version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}/" >> $GITHUB_ENV
      - name: Build docs
        run: cd ./api/rust && cargo doc --no-deps -p pinnacle-api -p tokio
      - name: Create index.html
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=pinnacle_api\">" > ./target/doc/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DOCS_DEPLOY_KEY_RUST }}
          external_repository: pinnacle-comp/rust-reference
          publish_dir: ./target/doc
          destination_dir: ${{ env.RELEASE_VERSION || 'main' }}
